vich_uploader:
    db_driver: orm
    mappings:
        traobject_pictures:
            uri_prefix:         '%app.path.traobject_pictures%'
            upload_destination: '%kernel.root_dir%/../public/%app.path.traobject_pictures%'
        user_pictures:
            uri_prefix:         '%app.path.user_pictures%'
            upload_destination: '%kernel.root_dir%/../public/%app.path.user_pictures%'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
